logFilters:
  - code: YN0002
    level: error
  - code: YN0060
    level: warning

nodeLinker: node-modules

packageExtensions:
  "@chakra-ui/accordion@1.3.1":
    peerDependencies:
      framer-motion: "*"
  "@chakra-ui/skeleton@1.1.12":
    peerDependencies:
      "@chakra-ui/theme": "*"
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/switch@1.2.5":
    peerDependencies:
      framer-motion: "*"
  "@endemolshinegroup/cosmiconfig-typescript-loader@3.0.2":
    peerDependencies:
      typescript: "*"
  "@graphql-codegen/cli@1.21.4":
    peerDependencies:
      typescript: "*"
  "@storybook/core-server@*":
    peerDependencies:
      "@babel/core": "*"
  "@storybook/core@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/csf-tools@*":
    peerDependencies:
      "@babel/core": "*"
  eslint-config-airbnb-typescript@12.3.1:
    peerDependencies:
      eslint: "*"
      eslint-plugin-import: "*"
      eslint-plugin-jsx-a11y: "*"
      eslint-plugin-react: "*"
      eslint-plugin-react-hooks: "*"
  graphql-config@3.3.0:
    peerDependencies:
      typescript: "*"
  next-pwa@*:
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  next@*:
    peerDependencies:
      "@babel/core": "*"
  react-dev-utils@11.0.4:
    peerDependencies:
      typescript: "*"
      webpack: "*"
  realistic-structured-clone@2.0.2:
    dependencies:
      core-js-bundle: "*"
      regenerator-runtime: "*"
  styled-jsx@*:
    peerDependencies:
      "@babel/core": "*"

yarnPath: .yarn/releases/yarn-3.0.1.cjs
